[tool.poetry]
name = "matrix-loading"
version = "0.1.0"
description = "Matrix data analysis pipeline for Module08 Exercise1"
authors = ["Aghvan Aleksanyan"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
pandas = "3.0.3"
numpy = "2.4.6"
matplotlib = "3.10.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"